server:
  port: 1020

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smc?serverTimezone=GMT
    username: root
    password: passw0rd
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    host: smtp.qq.com
    port: 465
    username: see-submission-file
    password: see-submission-file
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:1000/eureka
    healthcheck:
      enabled: true

smc:
  registration-confirm-url: https://localhost:4200/register-confirm/